[site]
# The site root (where index.html is output)
site-root = "target/site"

# The site package directory (where the CSS and JS are output)
site-pkg-dir = "pkg"

# The directory for static assets
assets-dir = "assets"

# The root name of the output CSS file
output-name = "kairos-ui"

[build]
# The name of the binary target used
bin-target = "kairos-ui"

# The features to use when compiling the bin target
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
# Optional. Defaults to false.
bin-default-features = false

# The name of the lib target used
lib-target = "kairos-ui"

# The features to use when compiling the lib target
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
# Optional. Defaults to false.
lib-default-features = false

[watch]
# The directory to watch for file changes
watch-root = "src"

# The port to serve on. Defaults to 3000
port = 3001

# Reload port. Defaults to 3001
reload-port = 3002

# Static file server. When enabled, the server will also serve files from the site root.
# This is useful for serving static assets.
static-site = true

[tool]
# Set by cargo-leptos
leptos = {}