name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the Docker image (multi-platform)
      run: docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag kairos-rs:$(date +%s) .
